In [2]:
import pandas as pd
import plotly.graph_objects as go
import numpy as np
import plotly.express as px

In [3]:
result=pd.read_csv("survey_42.csv")
result=result.iloc[2:]

In [4]:
result.drop(25)

,Horodateur,"Regarding microscopic traffic simulation tools, what is your expertise level?\n[from no expertise (= I know what it is done for, but I do not use it ) to advanced level (= I practice it regularly) and expert level (= I practice it, contribute to develop car-following model and/or have years of experience in the domain).",Please select one of the following pictures. It will assign you to a specific set of side-by-side comparisons.,"Among the 4 scenarios studied so far, please provide your opinion on the level of confidence we can have in the criticality indicators provided by the simulation tool.\n\n\nIf you are unsure and hesitate between two values, you can note both. Two scenarios may have the same confidence level. [Sunny]","Among the 4 scenarios studied so far, please provide your opinion on the level of confidence we can have in the criticality indicators provided by the simulation tool.\n\n\nIf you are unsure and hesitate between two values, you can note both. Two scenarios may have the same confidence level. [Cloudy]","Among the 4 scenarios studied so far, please provide your opinion on the level of confidence we can have in the criticality indicators provided by the simulation tool.\n\n\nIf you are unsure and hesitate between two values, you can note both. Two scenarios may have the same confidence level. [Night]","Among the 4 scenarios studied so far, please provide your opinion on the level of confidence we can have in the criticality indicators provided by the simulation tool.\n\n\nIf you are unsure and hesitate between two values, you can note both. Two scenarios may have the same confidence level. [Night w/ artificial illumination]","In this question, we will consider a sunny condition scenario and compare it with another condition. In which scenario would you have the most confidence in the representations of risk indicators (for example, TTC) in comparison with the sunny scenario? [Cloudy]","In this question, we will consider a sunny condition scenario and compare it with another condition. In which scenario would you have the most confidence in the representations of risk indicators (for example, TTC) in comparison with the sunny scenario? [Night]","In this question, we will consider a sunny condition scenario and compare it with another condition. In which scenario would you have the most confidence in the representations of risk indicators (for example, TTC) in comparison with the sunny scenario? [Night w/ Artificial Illumination]",...,"In this question, we will consider a Curved Geometry scenario and compare it with the other scenarios. In which scenario would you have the most confidence in the representations of risk indicators (for example, TTC) in comparison with a curved road scenario? [Up-Slope]","In this question, we will consider a Curved Geometry scenario and compare it with the other scenarios. In which scenario would you have the most confidence in the representations of risk indicators (for example, TTC) in comparison with a curved road scenario? [Downward-Slope]","In this question, we will consider Up-Slope Geometry scenario and compare it with the other scenarios. In which scenario would you have the most confidence in the representations of risk indicators (for example, TTC)? [Risk Indicator Confidence (e.g TTC)]",Comparative Scenario:\n\nWe now have two scenarios: a curved geometry situation and a junction road. Please indicate which of these scenarios you would have more confidence in regarding the criticality indicators that the scenario produces? [Risk Indicator Confidence (e.g TTC)],"Before moving on to the last section of the questionnaire (only 4 questions), do you have any remarks or comments?.6","Comparison 1\n\nAccording to an urban scenario and a highway scenario, please assign your level of confidence in the representations of risk indicators (e.g., TTC) by a simulation tool. [Risk Indicator Confidence (e.g TTC)]","Comparison 2\n\nAccording to an car-following scenario and a lane-changing scenario, please assign your level of confidence in the representations of risk indicators (e.g., TTC) by a simulation tool.\n\nReminder: Various models can be applied, ranging from Krauss for lane changing to GM for car following. [Risk Indicator Confidence (e.g TTC)]","Comparison 3\n\nAccording to a free flow scenario and a congested flow scenario, please assign your level of confidence in the representations of risk indicators (e.g., TTC) by a simulation tool. [Risk Indicator Confidence (e.g TTC)]","Comparison 4\n\nAccording to a straight way scenario and a turn scenario, please assign your level of confidence in the representations of risk indicators (e.g., TTC) by a simulation tool. [Risk Indicator Confidence (e.g TTC)]",Do you have any remarks or comments?
2,10/01/2024 15:40:59,Intermediate Level,Intersection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,A bit in urban,A bit in car-following,Strongly in free-flow,Strongly in straight,NaN
3,18/01/2024 08:14:57,Expert Level,Type of user,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Equally,A bit in car-following,A bit in free-flow,A bit in straight,Assessing safety from microscopic traffic simu...
4,19/01/2024 14:07:37,Advanced Level,Curved road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Strongly in this case,A bit in this case,Strongly in Upward-slope,Extremely in Curve,RAS,Equally,Strongly in car-following,Strongly in free-flow,A bit in turn,NaN
5,19/01/2024 14:27:02,Advanced Level,Intersection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,A bit in highway,A bit in lane-chaning,A bit in congestioned-flow,Equally,NaN
6,19/01/2024 15:26:03,Intermediate Level,Intersection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in highway,Strongly in car-following,Strongly in congestioned-flow,A bit in turn,NaN
7,20/01/2024 03:34:42,Intermediate Level,Driver's Vision,Strongly confident,Moderately confident,Low confidence,Not confident,A bit in this condition,Extremely in sunny,Extremely in sunny,...,NaN,NaN,NaN,NaN,NaN,Extremely in highway,Extremely in car-following,Equally,Extremely in straight,NaN
8,21/01/2024 16:57:42,Intermediate Level,Exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,22/01/2024 08:02:28,Beginner Level,Exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,22/01/2024 09:29:25,Expert Level,Specific Lane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,A bit in highway,Strongly in car-following,Strongly in free-flow,Equally,NaN
11,22/01/2024 09:34:00,Beginner Level,Type of user,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,A bit in highway,Strongly in car-following,Strongly in free-flow,Strongly in straight,NaN
12,08/02/2024 11:25:21,Expert Level,Intersection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,A bit in urban,Strongly in car-following,Strongly in free-flow,Strongly in turn,NaN
13,14/02/2024 09:18:20,No expertise,Type of user,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in highway,Strongly in car-following,Strongly in free-flow,A bit in straight,NaN
14,14/02/2024 09:37:01,Advanced Level,Sunny,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,A bit in highway,A bit in car-following,Strongly in free-flow,Strongly in straight,NaN
15,14/02/2024 10:02:35,No expertise,Driver's Vision,Extermely confident,Extermely confident,Moderately confident,Moderately confident,Equally,Strongly in sunny,Strongly in sunny,...,NaN,NaN,NaN,NaN,NaN,Strongly in highway,Extremely in car-following,Extremely in free-flow,Equally,NaN
16,15/02/2024 08:18:29,Expert Level,Type of user,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in highway,Strongly in car-following,Strongly in free-flow,A bit in straight,I worked on surrogate safety measures for driv...
17,15/02/2024 13:16:46,No expertise,Intersection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Extremely in highway,Extremely in car-following,Strongly in congestioned-flow,Strongly in straight,NaN
18,15/02/2024 15:24:36,Advanced Level,Exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rappelle tes indicateurs critiques avant qu'on...
19,19/02/2024 09:51:45,Expert Level,Type of user,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Equally,A bit in car-following,Equally,Equally,Instead of asking to the participants their le...
20,20/02/2024 21:21:26,Expert Level,Sunny,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Extremely in highway,Extremely in car-following,Equally,Extremely in straight,NaN
21,20/02/2024 21:22:48,Expert Level,Exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,21/02/2024 14:00:31,No expertise,Driver's Vision,Strongly confident,Moderately confident,Low confidence,Not confident,A bit in sunny,Strongly in sunny,Extremely in sunny,...,NaN,NaN,NaN,NaN,NaN,A bit in urban,Strongly in lane-chaning,A bit in free-flow,A bit in turn,Good luck
23,03/03/2024 06:21:41,Expert Level,Specific Lane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in highway,Strongly in car-following,Equally,Strongly in straight,Thanks and good luck!
24,07/03/2024 15:22:30,Intermediate Level,Intersection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in highway,Extremely in car-following,Equally,Equally,NaN
26,02/04/2024 17:59:54,Intermediate Level,Curved road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Strongly in Curve,Strongly in Curve,A bit in Downward-slope,Extremely in Curve,"For up and down slopes, it depends a lot on th...",Strongly in highway,Strongly in car-following,Strongly in free-flow,A bit in straight,NaN
27,02/04/2024 18:06:47,Intermediate Level,Type of user,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in highway,Strongly in car-following,Extremely in free-flow,A bit in straight,NaN
28,02/04/2024 18:22:22,Intermediate Level,Sunny,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in highway,Strongly in car-following,Extremely in free-flow,A bit in straight,NaN
29,02/04/2024 18:28:28,Intermediate Level,Specific Lane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in highway,Strongly in car-following,Extremely in free-flow,A bit in straight,NaN
30,02/04/2024 18:32:12,Intermediate Level,Driver's Vision,Extermely confident,Low confidence,Low confidence,Low confidence,Extremely in sunny,Extremely in sunny,Extremely in sunny,...,NaN,NaN,NaN,NaN,NaN,Strongly in highway,Strongly in car-following,Extremely in free-flow,A bit in straight,NaN
31,02/04/2024 18:35:48,Intermediate Level,Exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in highway,Strongly in car-following,Extremely in free-flow,A bit in straight,NaN
32,02/04/2024 18:39:02,Intermediate Level,Intersection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in highway,Strongly in car-following,Extremely in free-flow,A bit in straight,NaN
33,30/06/2024 01:53:06,No expertise,Type of user,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in urban,Strongly in car-following,Strongly in free-flow,Strongly in straight,NaN
34,13/07/2024 07:29:16,Beginner Level,Specific Lane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in highway,Strongly in car-following,A bit in free-flow,Strongly in straight,I don't know what TTC is.
35,13/07/2024 14:10:15,Expert Level,Exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in highway,Strongly in car-following,Strongly in free-flow,Strongly in straight,NaN
36,15/07/2024 05:43:12,Intermediate Level,Type of user,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in urban,Strongly in car-following,Strongly in free-flow,Strongly in straight,NaN
37,16/07/2024 02:41:31,Intermediate Level,Type of user,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Extremely in highway,Extremely in car-following,Extremely in free-flow,Extremely in straight,NaN
38,16/07/2024 02:51:50,Beginner Level,Specific Lane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,A bit in urban,Strongly in lane-chaning,Strongly in congested-flow,A bit in straight,NaN
39,16/07/2024 04:01:04,Advanced Level,Specific Lane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Extremely in highway,Extremely in car-following,Extremely in free-flow,Extremely in straight,NaN
40,12/08/2024 08:08:40,Expert Level,Exit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Equally,Strongly in car-following,A bit in free-flow,Equally,NaN
41,12/08/2024 14:00:42,Advanced Level,Intersection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in urban,A bit in lane-chaning,Strongly in congested-flow,Equally,NaN
42,15/08/2024 06:16:51,Advanced Level,Intersection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in highway,Strongly in car-following,Equally,Equally,No
43,19/08/2024 05:47:20,Advanced Level,Intersection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Strongly in urban,Equally,Strongly in free-flow,Equally,NaN

In [17]:
result.index(36)

TypeError: 'RangeIndex' object is not callable

In [8]:
##### Plot expertise

expertise_columns=result.columns[1]
fig = go.Figure()
colors = px.colors.qualitative.D3
fig.add_trace(go.Pie(labels=list(result[expertise_columns].value_counts().index),values=list(result[expertise_columns].value_counts())))
fig.update_traces( textfont_size=20,
                  marker=dict(colors=colors, line=dict(color='#000000', width=1)))

fig.update_layout(legend=dict( orientation="h", yanchor="middle", y=-0.20, x=0.19, title_font_family="Times New Roman",
 ))
fig.update_layout( width=600, height=600)


fig.show()
fig.write_image("images/expert_count.pdf")

In [14]:
##### Plot expertise

import plotly.graph_objects as go

expertise_columns=result.columns[2]

pivot_table=result.pivot_table(index=result.columns[1], columns=result.columns[2], aggfunc='size', fill_value=0)
desired_order = ['Intermediate Level', 'Expert Level', 'Advanced Level', 'Beginner Level', 'No expertise']

# Réorganiser les index selon l'ordre désiré
pivot_table = pivot_table.reindex(desired_order)

table_by_expert=[]
for i in range(0,len(pivot_table)):
    table_by_expert.append(list(pivot_table.iloc[i]))

In [18]:
fig=go.Figure()
for i in range(0,len(table_by_expert)):
    fig.add_trace(go.Bar(x=pivot_table.columns,y=table_by_expert[i],name=desired_order[i],marker_color=colors[i]))
fig.update_layout(barmode='stack')
fig.update_layout(legend=dict( orientation="h", yanchor="middle", y=-0.20, xanchor="center", x=0.5, title_font_family="Times New Roman",
 ))
fig.update_xaxes(title_text="<b>Scenario</b>")
fig.update_xaxes(title_text="<b>Count</b>")
fig.update_traces( textfont_size=30,
                  marker=dict(line=dict(color='#000000', width=1)))
fig.update_layout( width=800, height=800)
fig.update_layout( plot_bgcolor='rgb(245, 245, 245)')
fig.write_image("images/expert_scenario.pdf")
fig.show()

### Test d'un plot

In [9]:
list_comparaison_str=['Extremely in highway','Strongly in highway','A bit in highway','Equality'
                      ,'A bit in highway','Strongly in highway','Extremely in highway']
list_comparaison_num=[1/4,1/2,1/2,1,2,3,4]
list_comparaison_num=1/np.array(list_comparaison_num)
list_answer=list(result[result.columns[-5]])
list_answer_num=[]
for i in list_answer:
    list_answer_num.append(list_comparaison_num[list_comparaison_str.index(i)])

ValueError: 'A bit in urban' is not in list

In [10]:

q1 = np.percentile(list_answer_num, 18.75)
median = np.median(list_answer_num)
q3 = np.percentile(list_answer_num, 100-18.75)

IndexError: cannot do a non-empty take from an empty axes.

In [12]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default='notebook'

In [11]:
fig = make_subplots(rows=2, cols=1)

fig.add_trace(go.Scatter(x=[q1,median],y=[0,1],mode='lines',line=dict(color='#DC3912')),row=1, col=1)
fig.add_trace(go.Scatter(x=[median,q3],y=[1,0],mode='lines',line=dict(color='#DC3912')),row=1, col=1)


fig.add_trace(go.Box(x=list_answer_num,name="Reponse",marker=dict(
        color='#DC3912'  # Choisir la couleur souhaitée
    )),row=2, col=1)

fig.update_yaxes( 
            showgrid = True,
            
              showline = True,
              gridcolor = 'rgb(200,200,200)',
              gridwidth = 2,
              zerolinecolor = '#969696',
              zerolinewidth = 2,
              linecolor = 'rgb(253, 253, 253)',
              linewidth = 2,
              color ='rgb(55,126,184)',
                        title_text='Fuzzy Number',row=1, col=1
        )
fig.update_xaxes(   showgrid = True,
            
              showline = True,
              gridcolor = 'rgb(200,200,200)',
              gridwidth = 2,
              zerolinecolor = '#969696',
              zerolinewidth = 2,
              linecolor = 'rgb(253, 253, 253)',
              linewidth = 2,
              color ='rgb(55,126,184)',
     title_text='Value',
range=[1-0.2, 4+0.2]
) 

fig.update_layout(
plot_bgcolor= 'rgb(253, 253, 253)',
 showlegend=False ,
title_x=0.5
)

fig.show()

NameError: name 'make_subplots' is not defined

In [7]:
data=[[(1,1,1),(q1,median,q3)],[(1/q3,1/median,1/q1),(1,1,1)]]

pd.DataFrame(data,columns=["Highway","Urban"])

           Highway            Urban
0        (1, 1, 1)  (2.0, 2.0, 2.5)
1  (0.4, 0.5, 0.5)        (1, 1, 1)

In [116]:
q1

2.0